Sourcery - a web-based astronomical source list browser and manager
-------------------------------------------------------------------

Installation
------------

To install the Sourcery python module:

% sudo python setup.py install

Then the cgi-bin/ folder needs to be copied to a webserver and the 
sourcery.config file edited appropriately.

Requirements
------------
* astLib (pyfits, numpy, scipy)
* cherrypy (3.0+)
* ATpy (which depends on asciitable)

** Note that for running on apache, only ATpy 0.9.6 works, because astropy causes the following...

[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225] Traceback (most recent call last):
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]   File "/home/xcs/public_html/sourcery/cgi-bin/test.wsgi", line 21, in <module>
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]     import atpy
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]   File "/usr/local/lib/python2.7/dist-packages/ATpy-0.9.7-py2.7.egg/atpy/__init__.py", line 1, in <module>
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]     from .basetable import Table, TableSet, VectorException
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]   File "/usr/local/lib/python2.7/dist-packages/ATpy-0.9.7-py2.7.egg/atpy/basetable.py", line 15, in <module>
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]     from . import registry
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]   File "/usr/local/lib/python2.7/dist-packages/ATpy-0.9.7-py2.7.egg/atpy/registry.py", line 164, in <module>
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]     from . import fitstable
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]   File "/usr/local/lib/python2.7/dist-packages/ATpy-0.9.7-py2.7.egg/atpy/fitstable.py", line 6, in <module>
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]     from astropy.io import fits
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]   File "/usr/local/lib/python2.7/dist-packages/astropy/__init__.py", line 246, in <module>
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]     _initialize_astropy()
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]   File "/usr/local/lib/python2.7/dist-packages/astropy/__init__.py", line 228, in _initialize_astropy
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]     config.configuration.update_default_config(__package__, config_dir)
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]   File "/usr/local/lib/python2.7/dist-packages/astropy/config/configuration.py", line 695, in update_default_config
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]     if path.exists(cfgfn):
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]   File "/usr/lib/python2.7/genericpath.py", line 18, in exists
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225]     os.stat(path)
[Tue Jun 17 18:56:37 2014] [error] [client 41.150.225.225] TypeError: coercing to Unicode: need string or buffer, NoneType found

scipy interpolate is also a problem, apparently need to add the following to apache2 config:
    
    WSGIApplicationGroup %{GLOBAL}
    
Just add this at the end of /etc/apache2/apache2.conf in Ubuntu.

